# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: remote ssh command
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check node
      run: node --version
      
    - name: install lighthouse
      run: npm install -g lighthouse
    
    - name: chrom
      run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      
    - name: 4535345
      run: sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      
    - name: tests
      run: sudo apt-get update
      
    - name: tests
      run: sudo apt-get install google-chrome-stable
      
    - name: check lighthouse
      run: lighthouse --version
      
    - name: fdfdfd
      run: which google-chrome
      
    - name: lighthouse
      run: lighthouse google.com
