# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: remote ssh command
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check node
      run: node --version
      
    - name: install lighthouse
      run: npm install -g lighthouse
      
    - name: check lighthouse
      run: lighthouse --version
