# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: remote ssh command
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check node
      run: node --version
      
    - name: install lighthouse
      run: npm install -g lighthouse
    
    - name: chrom
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      
    - name: 4535345
      run: sudo dpkg -i ./google-chrome*.deb
      
    - name: tests
      run: sudo apt-get install -f
      
    - name: check lighthouse
      run: lighthouse --version
      
    - name: fdfdfd
      run: which google-chrome
      
    - name: lighthouse
      run: lighthouse google.com
